trigger:
- main  # Run the pipeline when changes are pushed to the "main" branch

pool:
  name: Default  

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Use the latest Python 3 version
  displayName: 'Set up Python'

- script: |
    python -m pip install --upgrade pip
    if exist requirements.txt pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: python Azure_devops/addition.py
  displayName: 'Run Python Script'

